### ISSUE TITLE
Need to update wiki

### ISSUE THREAD

**Issue by xBigG** [TheAmazingAussie/Icarus#1]
This is what I get when I try to compile on linux:
http://prntscr.com/enor74
Probably you removed some files? 👍 

Also, if you remove these files it doesn't compile anyway.

**Comment by TheAmazingAussie** [comment]
Sorry, I didn't see your ticket until now.

I updated and fixed the command yesterday, as I was testing Icarus on my Linux server, please let me know if you're still having trouble!

**Comment by xBigG** [comment]
Still can't compile.
If you can tell me what log you need i'll post it.

**Comment by TheAmazingAussie** [comment]
I also had to update the source to make it compilable as well, default was a reserved C++ keyword.

Please re-clone the repo and run the command again, I just tried it and it works. 😀

**Comment by xBigG** [comment]
I figured it out.
This is what I did:

1.  Re-cloning the repo
2.  Trying to recompile (errors, lot of mysql.h not found)
3.  I ran this command:
4.  **apt-get install libmysqlclient-dev** 
5.  Re-tryied, I've got other errors: -lboost_system not found etc.
6.  I installed this:
7.  **sudo apt-get install libboost-all-dev**
8.  Done.

**Comment by TheAmazingAussie** [comment]
Oh my, I feel incredibly stupid for not adding the result of the commands... I will update the readme when I'm home, as of right now I'm currently at university.

Thanks :)
